package turillolucastudente;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Turillo.Luca
 */
public class FrameStudente extends javax.swing.JFrame {

    private Studente[] s;
    private Integer dim = 5;
    private Integer cont = 0;
    private Integer voti[];
    private Double media = 0.0;

    public FrameStudente() {
        initComponents();
        s = new Studente[dim];
        this.setLocation(400, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblCognome = new javax.swing.JLabel();
        lblVoti = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCognome = new javax.swing.JTextField();
        btnCaricaStudente = new javax.swing.JButton();
        lblClasse = new javax.swing.JLabel();
        cmbClasse = new javax.swing.JComboBox<>();
        btnVoti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxStampa = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnStampa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        lblNome.setText("Nome:");

        lblCognome.setText("Cognome:");

        lblVoti.setText("Voti:");

        btnCaricaStudente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCaricaStudente.setText("Carica studente");
        btnCaricaStudente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaricaStudenteActionPerformed(evt);
            }
        });

        lblClasse.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblClasse.setText("Classe:");

        cmbClasse.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btnVoti.setText("Inserisci Voti");
        btnVoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotiActionPerformed(evt);
            }
        });

        atxStampa.setColumns(20);
        atxStampa.setRows(5);
        atxStampa.setFocusable(false);
        jScrollPane1.setViewportView(atxStampa);

        jLabel1.setText("Grandezza classe:  5");

        btnStampa.setText("Stampa");
        btnStampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStampaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNome)
                                    .addGap(77, 77, 77)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblVoti)
                                    .addGap(89, 89, 89)
                                    .addComponent(btnVoti, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCognome)
                                    .addGap(57, 57, 57)
                                    .addComponent(txtCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnCaricaStudente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(lblClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(cmbClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addComponent(btnStampa))))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCognome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoti)
                    .addComponent(lblVoti))
                .addGap(44, 44, 44)
                .addComponent(btnCaricaStudente)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClasse)
                    .addComponent(btnStampa))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaricaStudenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaricaStudenteActionPerformed
        String nome = txtNome.getText();
        String cognome = txtCognome.getText();
        cmbClasse.addItem(nome + ", " + cognome + ", Voti: " + Arrays.toString(voti));
        s[cont] = new Studente(nome, cognome, voti);
        s[cont].setMedia(media);
        txtNome.setText("");
        txtCognome.setText("");
        cont++;
    }//GEN-LAST:event_btnCaricaStudenteActionPerformed

    private void btnVotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotiActionPerformed
        voti = new Integer[5];
        Integer somma = 0;
        for (int i = 0; i < 5; i++) {
            somma += voti[i] = Integer.valueOf(JOptionPane.showInputDialog(this, "Voto " + (i + 1) + ": "));
        }
        media = Double.valueOf(somma) / 5;
    }//GEN-LAST:event_btnVotiActionPerformed

    private void btnStampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStampaActionPerformed
        Integer pos = cmbClasse.getSelectedIndex();
        atxStampa.append(s[pos].toString() + "\n");
    }//GEN-LAST:event_btnStampaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxStampa;
    private javax.swing.JButton btnCaricaStudente;
    private javax.swing.JButton btnStampa;
    private javax.swing.JButton btnVoti;
    private javax.swing.JComboBox<String> cmbClasse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClasse;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblVoti;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
